create table researches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  author text not null,
  file_url text not null,
  uploaded_by text
);

alter table researches enable row level security;

create policy "Anyone can view researches"
on researches for select
using (true);

create policy "Authenticated users can upload researches"
on researches for insert
to authenticated
with check (true);